-- Run this entire file once in your Supabase SQL Editor.
-- All 17 migrations combined.
-- See individual supabase/migrations/ files for full content.
-- Upload the full database/schema.sql from the zip for the complete schema.
