/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TeacherRouteImport } from './routes/teacher'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TeacherIndexRouteImport } from './routes/teacher/index'
import { Route as TeacherTransportRouteImport } from './routes/teacher/transport'
import { Route as TeacherTimetableRouteImport } from './routes/teacher/timetable'
import { Route as TeacherSubjectsRouteImport } from './routes/teacher/subjects'
import { Route as TeacherMarksRouteImport } from './routes/teacher/marks'
import { Route as TeacherLeaveRouteImport } from './routes/teacher/leave'
import { Route as TeacherDashboardRouteImport } from './routes/teacher/dashboard'
import { Route as TeacherClassesRouteImport } from './routes/teacher/classes'
import { Route as TeacherAttendanceRouteImport } from './routes/teacher/attendance'
import { Route as AuthenticatedTimetableRouteImport } from './routes/_authenticated/timetable'
import { Route as AuthenticatedSubjectsRouteImport } from './routes/_authenticated/subjects'
import { Route as AuthenticatedStudentsRouteImport } from './routes/_authenticated/students'
import { Route as AuthenticatedStudentLedgerRouteImport } from './routes/_authenticated/student-ledger'
import { Route as AuthenticatedStaffDashboardRouteImport } from './routes/_authenticated/staff-dashboard'
import { Route as AuthenticatedStaffRouteImport } from './routes/_authenticated/staff'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedReportsRouteImport } from './routes/_authenticated/reports'
import { Route as AuthenticatedPayrollRouteImport } from './routes/_authenticated/payroll'
import { Route as AuthenticatedMyPerformanceRouteImport } from './routes/_authenticated/my-performance'
import { Route as AuthenticatedMyLeaveRouteImport } from './routes/_authenticated/my-leave'
import { Route as AuthenticatedMyFeesRouteImport } from './routes/_authenticated/my-fees'
import { Route as AuthenticatedMyChildrenRouteImport } from './routes/_authenticated/my-children'
import { Route as AuthenticatedMyAttendanceRouteImport } from './routes/_authenticated/my-attendance'
import { Route as AuthenticatedLeaveRequestsRouteImport } from './routes/_authenticated/leave-requests'
import { Route as AuthenticatedFinancialStatementRouteImport } from './routes/_authenticated/financial-statement'
import { Route as AuthenticatedFinanceOverviewRouteImport } from './routes/_authenticated/finance-overview'
import { Route as AuthenticatedFinanceRouteImport } from './routes/_authenticated/finance'
import { Route as AuthenticatedFeeStructureRouteImport } from './routes/_authenticated/fee-structure'
import { Route as AuthenticatedExamsRouteImport } from './routes/_authenticated/exams'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedClassesRouteImport } from './routes/_authenticated/classes'
import { Route as AuthenticatedBusRouteImport } from './routes/_authenticated/bus'
import { Route as AuthenticatedAttendanceRouteImport } from './routes/_authenticated/attendance'
import { Route as AuthenticatedAnnouncementsRouteImport } from './routes/_authenticated/announcements'
import { Route as AuthenticatedAllPaymentsRouteImport } from './routes/_authenticated/all-payments'
import { Route as AuthenticatedAccountsRouteImport } from './routes/_authenticated/accounts'
import { Route as AuthenticatedPageRouteImport } from './routes/_authenticated/$page'
import { Route as TeacherClassesClassIdRouteImport } from './routes/teacher/classes.$classId'

const TeacherRoute = TeacherRouteImport.update({
  id: '/teacher',
  path: '/teacher',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TeacherIndexRoute = TeacherIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TeacherRoute,
} as any)
const TeacherTransportRoute = TeacherTransportRouteImport.update({
  id: '/transport',
  path: '/transport',
  getParentRoute: () => TeacherRoute,
} as any)
const TeacherTimetableRoute = TeacherTimetableRouteImport.update({
  id: '/timetable',
  path: '/timetable',
  getParentRoute: () => TeacherRoute,
} as any)
const TeacherSubjectsRoute = TeacherSubjectsRouteImport.update({
  id: '/subjects',
  path: '/subjects',
  getParentRoute: () => TeacherRoute,
} as any)
const TeacherMarksRoute = TeacherMarksRouteImport.update({
  id: '/marks',
  path: '/marks',
  getParentRoute: () => TeacherRoute,
} as any)
const TeacherLeaveRoute = TeacherLeaveRouteImport.update({
  id: '/leave',
  path: '/leave',
  getParentRoute: () => TeacherRoute,
} as any)
const TeacherDashboardRoute = TeacherDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => TeacherRoute,
} as any)
const TeacherClassesRoute = TeacherClassesRouteImport.update({
  id: '/classes',
  path: '/classes',
  getParentRoute: () => TeacherRoute,
} as any)
const TeacherAttendanceRoute = TeacherAttendanceRouteImport.update({
  id: '/attendance',
  path: '/attendance',
  getParentRoute: () => TeacherRoute,
} as any)
const AuthenticatedTimetableRoute = AuthenticatedTimetableRouteImport.update({
  id: '/timetable',
  path: '/timetable',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSubjectsRoute = AuthenticatedSubjectsRouteImport.update({
  id: '/subjects',
  path: '/subjects',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedStudentsRoute = AuthenticatedStudentsRouteImport.update({
  id: '/students',
  path: '/students',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedStudentLedgerRoute =
  AuthenticatedStudentLedgerRouteImport.update({
    id: '/student-ledger',
    path: '/student-ledger',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedStaffDashboardRoute =
  AuthenticatedStaffDashboardRouteImport.update({
    id: '/staff-dashboard',
    path: '/staff-dashboard',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedStaffRoute = AuthenticatedStaffRouteImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedReportsRoute = AuthenticatedReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPayrollRoute = AuthenticatedPayrollRouteImport.update({
  id: '/payroll',
  path: '/payroll',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedMyPerformanceRoute =
  AuthenticatedMyPerformanceRouteImport.update({
    id: '/my-performance',
    path: '/my-performance',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedMyLeaveRoute = AuthenticatedMyLeaveRouteImport.update({
  id: '/my-leave',
  path: '/my-leave',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedMyFeesRoute = AuthenticatedMyFeesRouteImport.update({
  id: '/my-fees',
  path: '/my-fees',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedMyChildrenRoute = AuthenticatedMyChildrenRouteImport.update({
  id: '/my-children',
  path: '/my-children',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedMyAttendanceRoute =
  AuthenticatedMyAttendanceRouteImport.update({
    id: '/my-attendance',
    path: '/my-attendance',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedLeaveRequestsRoute =
  AuthenticatedLeaveRequestsRouteImport.update({
    id: '/leave-requests',
    path: '/leave-requests',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedFinancialStatementRoute =
  AuthenticatedFinancialStatementRouteImport.update({
    id: '/financial-statement',
    path: '/financial-statement',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedFinanceOverviewRoute =
  AuthenticatedFinanceOverviewRouteImport.update({
    id: '/finance-overview',
    path: '/finance-overview',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedFinanceRoute = AuthenticatedFinanceRouteImport.update({
  id: '/finance',
  path: '/finance',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedFeeStructureRoute =
  AuthenticatedFeeStructureRouteImport.update({
    id: '/fee-structure',
    path: '/fee-structure',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedExamsRoute = AuthenticatedExamsRouteImport.update({
  id: '/exams',
  path: '/exams',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedClassesRoute = AuthenticatedClassesRouteImport.update({
  id: '/classes',
  path: '/classes',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedBusRoute = AuthenticatedBusRouteImport.update({
  id: '/bus',
  path: '/bus',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAttendanceRoute = AuthenticatedAttendanceRouteImport.update({
  id: '/attendance',
  path: '/attendance',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAnnouncementsRoute =
  AuthenticatedAnnouncementsRouteImport.update({
    id: '/announcements',
    path: '/announcements',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAllPaymentsRoute =
  AuthenticatedAllPaymentsRouteImport.update({
    id: '/all-payments',
    path: '/all-payments',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAccountsRoute = AuthenticatedAccountsRouteImport.update({
  id: '/accounts',
  path: '/accounts',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPageRoute = AuthenticatedPageRouteImport.update({
  id: '/$page',
  path: '/$page',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const TeacherClassesClassIdRoute = TeacherClassesClassIdRouteImport.update({
  id: '/$classId',
  path: '/$classId',
  getParentRoute: () => TeacherClassesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/teacher': typeof TeacherRouteWithChildren
  '/$page': typeof AuthenticatedPageRoute
  '/accounts': typeof AuthenticatedAccountsRoute
  '/all-payments': typeof AuthenticatedAllPaymentsRoute
  '/announcements': typeof AuthenticatedAnnouncementsRoute
  '/attendance': typeof AuthenticatedAttendanceRoute
  '/bus': typeof AuthenticatedBusRoute
  '/classes': typeof AuthenticatedClassesRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/exams': typeof AuthenticatedExamsRoute
  '/fee-structure': typeof AuthenticatedFeeStructureRoute
  '/finance': typeof AuthenticatedFinanceRoute
  '/finance-overview': typeof AuthenticatedFinanceOverviewRoute
  '/financial-statement': typeof AuthenticatedFinancialStatementRoute
  '/leave-requests': typeof AuthenticatedLeaveRequestsRoute
  '/my-attendance': typeof AuthenticatedMyAttendanceRoute
  '/my-children': typeof AuthenticatedMyChildrenRoute
  '/my-fees': typeof AuthenticatedMyFeesRoute
  '/my-leave': typeof AuthenticatedMyLeaveRoute
  '/my-performance': typeof AuthenticatedMyPerformanceRoute
  '/payroll': typeof AuthenticatedPayrollRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/staff': typeof AuthenticatedStaffRoute
  '/staff-dashboard': typeof AuthenticatedStaffDashboardRoute
  '/student-ledger': typeof AuthenticatedStudentLedgerRoute
  '/students': typeof AuthenticatedStudentsRoute
  '/subjects': typeof AuthenticatedSubjectsRoute
  '/timetable': typeof AuthenticatedTimetableRoute
  '/teacher/attendance': typeof TeacherAttendanceRoute
  '/teacher/classes': typeof TeacherClassesRouteWithChildren
  '/teacher/dashboard': typeof TeacherDashboardRoute
  '/teacher/leave': typeof TeacherLeaveRoute
  '/teacher/marks': typeof TeacherMarksRoute
  '/teacher/subjects': typeof TeacherSubjectsRoute
  '/teacher/timetable': typeof TeacherTimetableRoute
  '/teacher/transport': typeof TeacherTransportRoute
  '/teacher/': typeof TeacherIndexRoute
  '/teacher/classes/$classId': typeof TeacherClassesClassIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/$page': typeof AuthenticatedPageRoute
  '/accounts': typeof AuthenticatedAccountsRoute
  '/all-payments': typeof AuthenticatedAllPaymentsRoute
  '/announcements': typeof AuthenticatedAnnouncementsRoute
  '/attendance': typeof AuthenticatedAttendanceRoute
  '/bus': typeof AuthenticatedBusRoute
  '/classes': typeof AuthenticatedClassesRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/exams': typeof AuthenticatedExamsRoute
  '/fee-structure': typeof AuthenticatedFeeStructureRoute
  '/finance': typeof AuthenticatedFinanceRoute
  '/finance-overview': typeof AuthenticatedFinanceOverviewRoute
  '/financial-statement': typeof AuthenticatedFinancialStatementRoute
  '/leave-requests': typeof AuthenticatedLeaveRequestsRoute
  '/my-attendance': typeof AuthenticatedMyAttendanceRoute
  '/my-children': typeof AuthenticatedMyChildrenRoute
  '/my-fees': typeof AuthenticatedMyFeesRoute
  '/my-leave': typeof AuthenticatedMyLeaveRoute
  '/my-performance': typeof AuthenticatedMyPerformanceRoute
  '/payroll': typeof AuthenticatedPayrollRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/staff': typeof AuthenticatedStaffRoute
  '/staff-dashboard': typeof AuthenticatedStaffDashboardRoute
  '/student-ledger': typeof AuthenticatedStudentLedgerRoute
  '/students': typeof AuthenticatedStudentsRoute
  '/subjects': typeof AuthenticatedSubjectsRoute
  '/timetable': typeof AuthenticatedTimetableRoute
  '/teacher/attendance': typeof TeacherAttendanceRoute
  '/teacher/classes': typeof TeacherClassesRouteWithChildren
  '/teacher/dashboard': typeof TeacherDashboardRoute
  '/teacher/leave': typeof TeacherLeaveRoute
  '/teacher/marks': typeof TeacherMarksRoute
  '/teacher/subjects': typeof TeacherSubjectsRoute
  '/teacher/timetable': typeof TeacherTimetableRoute
  '/teacher/transport': typeof TeacherTransportRoute
  '/teacher': typeof TeacherIndexRoute
  '/teacher/classes/$classId': typeof TeacherClassesClassIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/auth': typeof AuthRoute
  '/teacher': typeof TeacherRouteWithChildren
  '/_authenticated/$page': typeof AuthenticatedPageRoute
  '/_authenticated/accounts': typeof AuthenticatedAccountsRoute
  '/_authenticated/all-payments': typeof AuthenticatedAllPaymentsRoute
  '/_authenticated/announcements': typeof AuthenticatedAnnouncementsRoute
  '/_authenticated/attendance': typeof AuthenticatedAttendanceRoute
  '/_authenticated/bus': typeof AuthenticatedBusRoute
  '/_authenticated/classes': typeof AuthenticatedClassesRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/exams': typeof AuthenticatedExamsRoute
  '/_authenticated/fee-structure': typeof AuthenticatedFeeStructureRoute
  '/_authenticated/finance': typeof AuthenticatedFinanceRoute
  '/_authenticated/finance-overview': typeof AuthenticatedFinanceOverviewRoute
  '/_authenticated/financial-statement': typeof AuthenticatedFinancialStatementRoute
  '/_authenticated/leave-requests': typeof AuthenticatedLeaveRequestsRoute
  '/_authenticated/my-attendance': typeof AuthenticatedMyAttendanceRoute
  '/_authenticated/my-children': typeof AuthenticatedMyChildrenRoute
  '/_authenticated/my-fees': typeof AuthenticatedMyFeesRoute
  '/_authenticated/my-leave': typeof AuthenticatedMyLeaveRoute
  '/_authenticated/my-performance': typeof AuthenticatedMyPerformanceRoute
  '/_authenticated/payroll': typeof AuthenticatedPayrollRoute
  '/_authenticated/reports': typeof AuthenticatedReportsRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/staff': typeof AuthenticatedStaffRoute
  '/_authenticated/staff-dashboard': typeof AuthenticatedStaffDashboardRoute
  '/_authenticated/student-ledger': typeof AuthenticatedStudentLedgerRoute
  '/_authenticated/students': typeof AuthenticatedStudentsRoute
  '/_authenticated/subjects': typeof AuthenticatedSubjectsRoute
  '/_authenticated/timetable': typeof AuthenticatedTimetableRoute
  '/teacher/attendance': typeof TeacherAttendanceRoute
  '/teacher/classes': typeof TeacherClassesRouteWithChildren
  '/teacher/dashboard': typeof TeacherDashboardRoute
  '/teacher/leave': typeof TeacherLeaveRoute
  '/teacher/marks': typeof TeacherMarksRoute
  '/teacher/subjects': typeof TeacherSubjectsRoute
  '/teacher/timetable': typeof TeacherTimetableRoute
  '/teacher/transport': typeof TeacherTransportRoute
  '/teacher/': typeof TeacherIndexRoute
  '/teacher/classes/$classId': typeof TeacherClassesClassIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/teacher'
    | '/$page'
    | '/accounts'
    | '/all-payments'
    | '/announcements'
    | '/attendance'
    | '/bus'
    | '/classes'
    | '/dashboard'
    | '/exams'
    | '/fee-structure'
    | '/finance'
    | '/finance-overview'
    | '/financial-statement'
    | '/leave-requests'
    | '/my-attendance'
    | '/my-children'
    | '/my-fees'
    | '/my-leave'
    | '/my-performance'
    | '/payroll'
    | '/reports'
    | '/settings'
    | '/staff'
    | '/staff-dashboard'
    | '/student-ledger'
    | '/students'
    | '/subjects'
    | '/timetable'
    | '/teacher/attendance'
    | '/teacher/classes'
    | '/teacher/dashboard'
    | '/teacher/leave'
    | '/teacher/marks'
    | '/teacher/subjects'
    | '/teacher/timetable'
    | '/teacher/transport'
    | '/teacher/'
    | '/teacher/classes/$classId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/$page'
    | '/accounts'
    | '/all-payments'
    | '/announcements'
    | '/attendance'
    | '/bus'
    | '/classes'
    | '/dashboard'
    | '/exams'
    | '/fee-structure'
    | '/finance'
    | '/finance-overview'
    | '/financial-statement'
    | '/leave-requests'
    | '/my-attendance'
    | '/my-children'
    | '/my-fees'
    | '/my-leave'
    | '/my-performance'
    | '/payroll'
    | '/reports'
    | '/settings'
    | '/staff'
    | '/staff-dashboard'
    | '/student-ledger'
    | '/students'
    | '/subjects'
    | '/timetable'
    | '/teacher/attendance'
    | '/teacher/classes'
    | '/teacher/dashboard'
    | '/teacher/leave'
    | '/teacher/marks'
    | '/teacher/subjects'
    | '/teacher/timetable'
    | '/teacher/transport'
    | '/teacher'
    | '/teacher/classes/$classId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/teacher'
    | '/_authenticated/$page'
    | '/_authenticated/accounts'
    | '/_authenticated/all-payments'
    | '/_authenticated/announcements'
    | '/_authenticated/attendance'
    | '/_authenticated/bus'
    | '/_authenticated/classes'
    | '/_authenticated/dashboard'
    | '/_authenticated/exams'
    | '/_authenticated/fee-structure'
    | '/_authenticated/finance'
    | '/_authenticated/finance-overview'
    | '/_authenticated/financial-statement'
    | '/_authenticated/leave-requests'
    | '/_authenticated/my-attendance'
    | '/_authenticated/my-children'
    | '/_authenticated/my-fees'
    | '/_authenticated/my-leave'
    | '/_authenticated/my-performance'
    | '/_authenticated/payroll'
    | '/_authenticated/reports'
    | '/_authenticated/settings'
    | '/_authenticated/staff'
    | '/_authenticated/staff-dashboard'
    | '/_authenticated/student-ledger'
    | '/_authenticated/students'
    | '/_authenticated/subjects'
    | '/_authenticated/timetable'
    | '/teacher/attendance'
    | '/teacher/classes'
    | '/teacher/dashboard'
    | '/teacher/leave'
    | '/teacher/marks'
    | '/teacher/subjects'
    | '/teacher/timetable'
    | '/teacher/transport'
    | '/teacher/'
    | '/teacher/classes/$classId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AuthRoute: typeof AuthRoute
  TeacherRoute: typeof TeacherRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/teacher': {
      id: '/teacher'
      path: '/teacher'
      fullPath: '/teacher'
      preLoaderRoute: typeof TeacherRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teacher/': {
      id: '/teacher/'
      path: '/'
      fullPath: '/teacher/'
      preLoaderRoute: typeof TeacherIndexRouteImport
      parentRoute: typeof TeacherRoute
    }
    '/teacher/transport': {
      id: '/teacher/transport'
      path: '/transport'
      fullPath: '/teacher/transport'
      preLoaderRoute: typeof TeacherTransportRouteImport
      parentRoute: typeof TeacherRoute
    }
    '/teacher/timetable': {
      id: '/teacher/timetable'
      path: '/timetable'
      fullPath: '/teacher/timetable'
      preLoaderRoute: typeof TeacherTimetableRouteImport
      parentRoute: typeof TeacherRoute
    }
    '/teacher/subjects': {
      id: '/teacher/subjects'
      path: '/subjects'
      fullPath: '/teacher/subjects'
      preLoaderRoute: typeof TeacherSubjectsRouteImport
      parentRoute: typeof TeacherRoute
    }
    '/teacher/marks': {
      id: '/teacher/marks'
      path: '/marks'
      fullPath: '/teacher/marks'
      preLoaderRoute: typeof TeacherMarksRouteImport
      parentRoute: typeof TeacherRoute
    }
    '/teacher/leave': {
      id: '/teacher/leave'
      path: '/leave'
      fullPath: '/teacher/leave'
      preLoaderRoute: typeof TeacherLeaveRouteImport
      parentRoute: typeof TeacherRoute
    }
    '/teacher/dashboard': {
      id: '/teacher/dashboard'
      path: '/dashboard'
      fullPath: '/teacher/dashboard'
      preLoaderRoute: typeof TeacherDashboardRouteImport
      parentRoute: typeof TeacherRoute
    }
    '/teacher/classes': {
      id: '/teacher/classes'
      path: '/classes'
      fullPath: '/teacher/classes'
      preLoaderRoute: typeof TeacherClassesRouteImport
      parentRoute: typeof TeacherRoute
    }
    '/teacher/attendance': {
      id: '/teacher/attendance'
      path: '/attendance'
      fullPath: '/teacher/attendance'
      preLoaderRoute: typeof TeacherAttendanceRouteImport
      parentRoute: typeof TeacherRoute
    }
    '/_authenticated/timetable': {
      id: '/_authenticated/timetable'
      path: '/timetable'
      fullPath: '/timetable'
      preLoaderRoute: typeof AuthenticatedTimetableRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/subjects': {
      id: '/_authenticated/subjects'
      path: '/subjects'
      fullPath: '/subjects'
      preLoaderRoute: typeof AuthenticatedSubjectsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/students': {
      id: '/_authenticated/students'
      path: '/students'
      fullPath: '/students'
      preLoaderRoute: typeof AuthenticatedStudentsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/student-ledger': {
      id: '/_authenticated/student-ledger'
      path: '/student-ledger'
      fullPath: '/student-ledger'
      preLoaderRoute: typeof AuthenticatedStudentLedgerRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/staff-dashboard': {
      id: '/_authenticated/staff-dashboard'
      path: '/staff-dashboard'
      fullPath: '/staff-dashboard'
      preLoaderRoute: typeof AuthenticatedStaffDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/staff': {
      id: '/_authenticated/staff'
      path: '/staff'
      fullPath: '/staff'
      preLoaderRoute: typeof AuthenticatedStaffRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/reports': {
      id: '/_authenticated/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AuthenticatedReportsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/payroll': {
      id: '/_authenticated/payroll'
      path: '/payroll'
      fullPath: '/payroll'
      preLoaderRoute: typeof AuthenticatedPayrollRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/my-performance': {
      id: '/_authenticated/my-performance'
      path: '/my-performance'
      fullPath: '/my-performance'
      preLoaderRoute: typeof AuthenticatedMyPerformanceRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/my-leave': {
      id: '/_authenticated/my-leave'
      path: '/my-leave'
      fullPath: '/my-leave'
      preLoaderRoute: typeof AuthenticatedMyLeaveRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/my-fees': {
      id: '/_authenticated/my-fees'
      path: '/my-fees'
      fullPath: '/my-fees'
      preLoaderRoute: typeof AuthenticatedMyFeesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/my-children': {
      id: '/_authenticated/my-children'
      path: '/my-children'
      fullPath: '/my-children'
      preLoaderRoute: typeof AuthenticatedMyChildrenRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/my-attendance': {
      id: '/_authenticated/my-attendance'
      path: '/my-attendance'
      fullPath: '/my-attendance'
      preLoaderRoute: typeof AuthenticatedMyAttendanceRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/leave-requests': {
      id: '/_authenticated/leave-requests'
      path: '/leave-requests'
      fullPath: '/leave-requests'
      preLoaderRoute: typeof AuthenticatedLeaveRequestsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/financial-statement': {
      id: '/_authenticated/financial-statement'
      path: '/financial-statement'
      fullPath: '/financial-statement'
      preLoaderRoute: typeof AuthenticatedFinancialStatementRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/finance-overview': {
      id: '/_authenticated/finance-overview'
      path: '/finance-overview'
      fullPath: '/finance-overview'
      preLoaderRoute: typeof AuthenticatedFinanceOverviewRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/finance': {
      id: '/_authenticated/finance'
      path: '/finance'
      fullPath: '/finance'
      preLoaderRoute: typeof AuthenticatedFinanceRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/fee-structure': {
      id: '/_authenticated/fee-structure'
      path: '/fee-structure'
      fullPath: '/fee-structure'
      preLoaderRoute: typeof AuthenticatedFeeStructureRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/exams': {
      id: '/_authenticated/exams'
      path: '/exams'
      fullPath: '/exams'
      preLoaderRoute: typeof AuthenticatedExamsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/classes': {
      id: '/_authenticated/classes'
      path: '/classes'
      fullPath: '/classes'
      preLoaderRoute: typeof AuthenticatedClassesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/bus': {
      id: '/_authenticated/bus'
      path: '/bus'
      fullPath: '/bus'
      preLoaderRoute: typeof AuthenticatedBusRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/attendance': {
      id: '/_authenticated/attendance'
      path: '/attendance'
      fullPath: '/attendance'
      preLoaderRoute: typeof AuthenticatedAttendanceRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/announcements': {
      id: '/_authenticated/announcements'
      path: '/announcements'
      fullPath: '/announcements'
      preLoaderRoute: typeof AuthenticatedAnnouncementsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/all-payments': {
      id: '/_authenticated/all-payments'
      path: '/all-payments'
      fullPath: '/all-payments'
      preLoaderRoute: typeof AuthenticatedAllPaymentsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/accounts': {
      id: '/_authenticated/accounts'
      path: '/accounts'
      fullPath: '/accounts'
      preLoaderRoute: typeof AuthenticatedAccountsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/$page': {
      id: '/_authenticated/$page'
      path: '/$page'
      fullPath: '/$page'
      preLoaderRoute: typeof AuthenticatedPageRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/teacher/classes/$classId': {
      id: '/teacher/classes/$classId'
      path: '/$classId'
      fullPath: '/teacher/classes/$classId'
      preLoaderRoute: typeof TeacherClassesClassIdRouteImport
      parentRoute: typeof TeacherClassesRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedPageRoute: typeof AuthenticatedPageRoute
  AuthenticatedAccountsRoute: typeof AuthenticatedAccountsRoute
  AuthenticatedAllPaymentsRoute: typeof AuthenticatedAllPaymentsRoute
  AuthenticatedAnnouncementsRoute: typeof AuthenticatedAnnouncementsRoute
  AuthenticatedAttendanceRoute: typeof AuthenticatedAttendanceRoute
  AuthenticatedBusRoute: typeof AuthenticatedBusRoute
  AuthenticatedClassesRoute: typeof AuthenticatedClassesRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedExamsRoute: typeof AuthenticatedExamsRoute
  AuthenticatedFeeStructureRoute: typeof AuthenticatedFeeStructureRoute
  AuthenticatedFinanceRoute: typeof AuthenticatedFinanceRoute
  AuthenticatedFinanceOverviewRoute: typeof AuthenticatedFinanceOverviewRoute
  AuthenticatedFinancialStatementRoute: typeof AuthenticatedFinancialStatementRoute
  AuthenticatedLeaveRequestsRoute: typeof AuthenticatedLeaveRequestsRoute
  AuthenticatedMyAttendanceRoute: typeof AuthenticatedMyAttendanceRoute
  AuthenticatedMyChildrenRoute: typeof AuthenticatedMyChildrenRoute
  AuthenticatedMyFeesRoute: typeof AuthenticatedMyFeesRoute
  AuthenticatedMyLeaveRoute: typeof AuthenticatedMyLeaveRoute
  AuthenticatedMyPerformanceRoute: typeof AuthenticatedMyPerformanceRoute
  AuthenticatedPayrollRoute: typeof AuthenticatedPayrollRoute
  AuthenticatedReportsRoute: typeof AuthenticatedReportsRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedStaffRoute: typeof AuthenticatedStaffRoute
  AuthenticatedStaffDashboardRoute: typeof AuthenticatedStaffDashboardRoute
  AuthenticatedStudentLedgerRoute: typeof AuthenticatedStudentLedgerRoute
  AuthenticatedStudentsRoute: typeof AuthenticatedStudentsRoute
  AuthenticatedSubjectsRoute: typeof AuthenticatedSubjectsRoute
  AuthenticatedTimetableRoute: typeof AuthenticatedTimetableRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedPageRoute: AuthenticatedPageRoute,
  AuthenticatedAccountsRoute: AuthenticatedAccountsRoute,
  AuthenticatedAllPaymentsRoute: AuthenticatedAllPaymentsRoute,
  AuthenticatedAnnouncementsRoute: AuthenticatedAnnouncementsRoute,
  AuthenticatedAttendanceRoute: AuthenticatedAttendanceRoute,
  AuthenticatedBusRoute: AuthenticatedBusRoute,
  AuthenticatedClassesRoute: AuthenticatedClassesRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedExamsRoute: AuthenticatedExamsRoute,
  AuthenticatedFeeStructureRoute: AuthenticatedFeeStructureRoute,
  AuthenticatedFinanceRoute: AuthenticatedFinanceRoute,
  AuthenticatedFinanceOverviewRoute: AuthenticatedFinanceOverviewRoute,
  AuthenticatedFinancialStatementRoute: AuthenticatedFinancialStatementRoute,
  AuthenticatedLeaveRequestsRoute: AuthenticatedLeaveRequestsRoute,
  AuthenticatedMyAttendanceRoute: AuthenticatedMyAttendanceRoute,
  AuthenticatedMyChildrenRoute: AuthenticatedMyChildrenRoute,
  AuthenticatedMyFeesRoute: AuthenticatedMyFeesRoute,
  AuthenticatedMyLeaveRoute: AuthenticatedMyLeaveRoute,
  AuthenticatedMyPerformanceRoute: AuthenticatedMyPerformanceRoute,
  AuthenticatedPayrollRoute: AuthenticatedPayrollRoute,
  AuthenticatedReportsRoute: AuthenticatedReportsRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedStaffRoute: AuthenticatedStaffRoute,
  AuthenticatedStaffDashboardRoute: AuthenticatedStaffDashboardRoute,
  AuthenticatedStudentLedgerRoute: AuthenticatedStudentLedgerRoute,
  AuthenticatedStudentsRoute: AuthenticatedStudentsRoute,
  AuthenticatedSubjectsRoute: AuthenticatedSubjectsRoute,
  AuthenticatedTimetableRoute: AuthenticatedTimetableRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

interface TeacherClassesRouteChildren {
  TeacherClassesClassIdRoute: typeof TeacherClassesClassIdRoute
}

const TeacherClassesRouteChildren: TeacherClassesRouteChildren = {
  TeacherClassesClassIdRoute: TeacherClassesClassIdRoute,
}

const TeacherClassesRouteWithChildren = TeacherClassesRoute._addFileChildren(
  TeacherClassesRouteChildren,
)

interface TeacherRouteChildren {
  TeacherAttendanceRoute: typeof TeacherAttendanceRoute
  TeacherClassesRoute: typeof TeacherClassesRouteWithChildren
  TeacherDashboardRoute: typeof TeacherDashboardRoute
  TeacherLeaveRoute: typeof TeacherLeaveRoute
  TeacherMarksRoute: typeof TeacherMarksRoute
  TeacherSubjectsRoute: typeof TeacherSubjectsRoute
  TeacherTimetableRoute: typeof TeacherTimetableRoute
  TeacherTransportRoute: typeof TeacherTransportRoute
  TeacherIndexRoute: typeof TeacherIndexRoute
}

const TeacherRouteChildren: TeacherRouteChildren = {
  TeacherAttendanceRoute: TeacherAttendanceRoute,
  TeacherClassesRoute: TeacherClassesRouteWithChildren,
  TeacherDashboardRoute: TeacherDashboardRoute,
  TeacherLeaveRoute: TeacherLeaveRoute,
  TeacherMarksRoute: TeacherMarksRoute,
  TeacherSubjectsRoute: TeacherSubjectsRoute,
  TeacherTimetableRoute: TeacherTimetableRoute,
  TeacherTransportRoute: TeacherTransportRoute,
  TeacherIndexRoute: TeacherIndexRoute,
}

const TeacherRouteWithChildren =
  TeacherRoute._addFileChildren(TeacherRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AuthRoute: AuthRoute,
  TeacherRoute: TeacherRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
